# -*- coding: utf-8 -*-
"""classification New...ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Orj17gu8m7H-bnFFUgZZDMQt2Qj-CHJW
"""

import os
import re
import json
import time
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")

# ----------------------------
# NLTK
# ----------------------------
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# ----------------------------
# Classical ML
# ----------------------------
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix,
    f1_score, precision_score, recall_score
)

from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV

import joblib

# ----------------------------
# Explainability
# ----------------------------
import shap
from lime.lime_text import LimeTextExplainer

# ----------------------------
# DistilBERT (PyTorch)
# ----------------------------
import torch
from torch.utils.data import Dataset
from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    Trainer,
    TrainingArguments
)

# ============================================================
# CONFIG
# ============================================================
DATA_PATH = "./cyberbullying_tweets.csv"
TEXT_COL = "tweet_text"
LABEL_COL = "cyberbullying_type"
DROP_LABEL = "other_cyberbullying"

RANDOM_STATE = 42
TEST_SIZE = 0.2

# Classical TF-IDF
TFIDF_MAX_FEATURES = 10000
TFIDF_NGRAM = (1, 2)

# DistilBERT
BERT_MODEL_NAME = "distilbert-base-uncased"
BERT_MAX_LENGTH = 96
BERT_EPOCHS = 1
BERT_TRAIN_BS = 16
BERT_EVAL_BS = 16
BERT_LR = 2e-5
BERT_MAX_STEPS = 500
BERT_TRAIN_SUBSET = 6000  # set None to train full; keep subset for speed

# Output dirs
OUT_DIR = "./artifacts_best"
CLASSICAL_DIR = "./artifacts_classical"
BERT_DIR = "./artifacts_distilbert"
os.makedirs(OUT_DIR, exist_ok=True)
os.makedirs(CLASSICAL_DIR, exist_ok=True)
os.makedirs(BERT_DIR, exist_ok=True)


# ============================================================
# TEXT CLEANING
# ============================================================
def ensure_nltk():
    nltk.download("stopwords", quiet=True)
    nltk.download("wordnet", quiet=True)
    nltk.download("omw-1.4", quiet=True)

_URL = re.compile(r"http\S+|www\.\S+")
_MENTION = re.compile(r"@\w+")
_HASH = re.compile(r"#")
_NONALPHA = re.compile(r"[^a-z\s]+")

def make_cleaner():
    sw = set(stopwords.words("english"))
    lem = WordNetLemmatizer()

    def clean(text):
        if text is None:
            return ""
        t = str(text).lower()
        t = _URL.sub(" ", t)
        t = _MENTION.sub(" ", t)
        t = _HASH.sub(" ", t)
        t = _NONALPHA.sub(" ", t)
        t = re.sub(r"\s+", " ", t).strip()
        if not t:
            return ""
        toks = [lem.lemmatize(w) for w in t.split() if w not in sw]
        return " ".join(toks)

    return clean

def safe_text(s, empty_token="[EMPTY]", max_chars=2000):
    if s is None:
        return empty_token
    t = str(s).strip()
    if not t:
        t = empty_token
    if len(t) > max_chars:
        t = t[:max_chars]
    return t


# ============================================================
# PLOTTING HELPERS (matplotlib only)
# ============================================================
def plot_bar_counts(series, title, xlabel, ylabel):
    counts = series.value_counts()
    plt.figure()
    counts.plot(kind="bar")
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.tight_layout()
    plt.show()

def plot_hist(values, title, xlabel, bins=40):
    plt.figure()
    plt.hist(values, bins=bins)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel("Frequency")
    plt.tight_layout()
    plt.show()

def plot_confusion(cm, class_names, title):
    plt.figure(figsize=(7, 6))
    plt.imshow(cm, interpolation="nearest")
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names, rotation=45, ha="right")
    plt.yticks(tick_marks, class_names)
    plt.xlabel("Predicted")
    plt.ylabel("Actual")

    # annotate
    thresh = cm.max() * 0.6 if cm.max() > 0 else 0.0
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            val = cm[i, j]
            plt.text(j, i, str(val), ha="center", va="center",
                     color="white" if val > thresh else "black")

    plt.tight_layout()
    plt.show()

def plot_model_comparison(df_metrics, title):
    # df_metrics: columns -> model, accuracy, f1_weighted, train_time_sec
    models = df_metrics["model"].tolist()
    acc = df_metrics["accuracy"].tolist()
    f1w = df_metrics["f1_weighted"].tolist()

    x = np.arange(len(models))
    w = 0.35

    plt.figure(figsize=(8, 4.5))
    plt.bar(x - w/2, acc, width=w, label="Accuracy")
    plt.bar(x + w/2, f1w, width=w, label="F1 (weighted)")
    plt.xticks(x, models, rotation=15)
    plt.ylim(0, 1.0)
    plt.title(title)
    plt.ylabel("Score")
    plt.legend()
    plt.tight_layout()
    plt.show()


# ============================================================
# 1) LOAD + BETTER EDA
# ============================================================
ensure_nltk()
df = pd.read_csv(DATA_PATH)
df = df.dropna(subset=[TEXT_COL, LABEL_COL]).copy()
if DROP_LABEL in df[LABEL_COL].unique():
    df = df[df[LABEL_COL] != DROP_LABEL].copy()

print("Dataset shape:", df.shape)
print("\nLabel distribution:")
print(df[LABEL_COL].value_counts())

plot_bar_counts(df[LABEL_COL], "Class Distribution", "Class", "Count")

# EDA: text length distribution (raw)
raw_len = df[TEXT_COL].astype(str).apply(lambda x: len(x))
plot_hist(raw_len.values, "Raw Tweet Length Distribution", "Chars")

# Clean text and EDA: cleaned length distribution
cleaner = make_cleaner()
df["clean_text"] = df[TEXT_COL].astype(str).apply(cleaner)

clean_len = df["clean_text"].apply(lambda x: len(x))
plot_hist(clean_len.values, "Cleaned Tweet Length Distribution", "Chars")

# Token count distribution (cleaned)
token_count = df["clean_text"].apply(lambda x: len(x.split()))
plot_hist(token_count.values, "Cleaned Token Count Distribution", "Tokens")

print("\nExamples (raw -> clean):")
for i in range(3):
    print("\nRAW:", df[TEXT_COL].iloc[i])
    print("CLN:", df["clean_text"].iloc[i])

# Top tokens overall (simple frequency)
cv = CountVectorizer(max_features=30)
X_counts = cv.fit_transform(df["clean_text"])
token_sums = np.asarray(X_counts.sum(axis=0)).ravel()
top_idx = token_sums.argsort()[::-1]
top_tokens = cv.get_feature_names_out()[top_idx]
top_vals = token_sums[top_idx]

plt.figure(figsize=(8, 5))
plt.barh(top_tokens[::-1], top_vals[::-1])
plt.title("Top 30 Tokens (Cleaned, Overall)")
plt.xlabel("Frequency")
plt.tight_layout()
plt.show()


# ============================================================
# 2) ENCODE + SPLIT
# ============================================================
label_encoder = LabelEncoder()
df["y"] = label_encoder.fit_transform(df[LABEL_COL].values)
class_names = list(label_encoder.classes_)

X = df["clean_text"].values
y = df["y"].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    stratify=y
)

print("\nTrain size:", len(X_train), "Test size:", len(X_test))
print("Classes:", class_names)


# ============================================================
# 3) CLASSICAL MODELS: CV COMPARISON + TEST REPORT + VISUALS
# ============================================================
def classical_candidates():
    return {
        "LogReg": LogisticRegression(max_iter=800),
        "NB": MultinomialNB(),
        "RF": RandomForestClassifier(n_estimators=300, random_state=RANDOM_STATE, n_jobs=-1),
        "Ridge": RidgeClassifier(),
        "SVM_Cal": CalibratedClassifierCV(LinearSVC(), method="sigmoid", cv=3),
    }

def make_classical_pipe(clf):
    return Pipeline([
        ("tfidf", TfidfVectorizer(
            ngram_range=TFIDF_NGRAM,
            max_features=TFIDF_MAX_FEATURES,
            sublinear_tf=True
        )),
        ("clf", clf)
    ])

print("\n==============================")
print("CLASSICAL: TRAIN + COMPARE")
print("==============================")

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

best_classical_name = None
best_classical_cv = -1.0
best_classical_pipe = None

classical_table = []

for name, clf in classical_candidates().items():
    pipe = make_classical_pipe(clf)

    scores = cross_validate(
        pipe, X_train, y_train, cv=skf,
        scoring={"acc": "accuracy", "f1w": "f1_weighted"},
        n_jobs=None
    )

    acc_mean = float(np.mean(scores["test_acc"]))
    f1w_mean = float(np.mean(scores["test_f1w"]))

    classical_table.append((name, acc_mean, f1w_mean))
    print(f"[CV] {name:7s}  acc={acc_mean:.4f}  f1w={f1w_mean:.4f}")

    if acc_mean > best_classical_cv:
        best_classical_cv = acc_mean
        best_classical_name = name
        best_classical_pipe = pipe

print("\nBest Classical by CV:", best_classical_name, "CV acc:", round(best_classical_cv, 4))

t0 = time.time()
best_classical_pipe.fit(X_train, y_train)
classical_train_time = time.time() - t0

y_pred_c = best_classical_pipe.predict(X_test)
classical_acc = float(accuracy_score(y_test, y_pred_c))
classical_f1w = float(f1_score(y_test, y_pred_c, average="weighted"))
classical_precw = float(precision_score(y_test, y_pred_c, average="weighted", zero_division=0))
classical_recw = float(recall_score(y_test, y_pred_c, average="weighted", zero_division=0))

print("\n[CLASSICAL TEST METRICS]")
print("Accuracy:", round(classical_acc, 4))
print("F1(w):  ", round(classical_f1w, 4))
print("\nClassification Report (Classical):\n")
print(classification_report(y_test, y_pred_c, target_names=class_names))

cm_c = confusion_matrix(y_test, y_pred_c)
plot_confusion(cm_c, class_names, "Confusion Matrix: Classical")

# Save classical artifacts
joblib.dump(best_classical_pipe, os.path.join(CLASSICAL_DIR, "best_model.pkl"))
joblib.dump(label_encoder, os.path.join(CLASSICAL_DIR, "label_encoder.pkl"))
with open(os.path.join(CLASSICAL_DIR, "metrics.json"), "w") as f:
    json.dump({
        "best_model_name": best_classical_name,
        "cv_accuracy": best_classical_cv,
        "test_accuracy": classical_acc,
        "test_f1_weighted": classical_f1w,
        "test_precision_weighted": classical_precw,
        "test_recall_weighted": classical_recw,
        "train_time_sec": classical_train_time
    }, f, indent=2)

print("Saved Classical artifacts ->", CLASSICAL_DIR)


# ============================================================
# 4) DISTILBERT: TRAIN + TEST REPORT + VISUALS
# ============================================================
print("\n==============================")
print("DISTILBERT: TRAIN + EVAL")
print("==============================")

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

tokenizer = DistilBertTokenizerFast.from_pretrained(BERT_MODEL_NAME)

class TextDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length):
        self.texts = list(texts)
        self.labels = list(labels)
        self.tok = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        txt = safe_text(self.texts[idx])
        enc = self.tok(
            txt,
            padding="max_length",
            truncation=True,
            max_length=self.max_length,
            return_tensors="pt"
        )
        item = {k: v.squeeze(0) for k, v in enc.items()}
        item["labels"] = torch.tensor(int(self.labels[idx]), dtype=torch.long)
        return item

# subset for speed (optional)
if BERT_TRAIN_SUBSET is not None and len(X_train) > BERT_TRAIN_SUBSET:
    X_train_b = X_train[:BERT_TRAIN_SUBSET]
    y_train_b = y_train[:BERT_TRAIN_SUBSET]
else:
    X_train_b = X_train
    y_train_b = y_train

train_ds = TextDataset(X_train_b, y_train_b, tokenizer, BERT_MAX_LENGTH)
test_ds  = TextDataset(X_test, y_test, tokenizer, BERT_MAX_LENGTH)

model = DistilBertForSequenceClassification.from_pretrained(
    BERT_MODEL_NAME,
    num_labels=len(class_names)
).to(device)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {"accuracy": float((preds == labels).mean())}

args = TrainingArguments(
    output_dir=BERT_DIR,
    num_train_epochs=BERT_EPOCHS,
    per_device_train_batch_size=BERT_TRAIN_BS,
    per_device_eval_batch_size=BERT_EVAL_BS,
    learning_rate=BERT_LR,
    eval_strategy="steps",
    eval_steps=100,
    logging_steps=50,
    save_strategy="no",
    report_to=[],
    fp16=torch.cuda.is_available(),
    max_steps=BERT_MAX_STEPS
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=test_ds,
    compute_metrics=compute_metrics
)

t0 = time.time()
trainer.train()
bert_train_time = time.time() - t0

bert_eval = trainer.evaluate()
bert_logits = trainer.predict(test_ds).predictions
y_pred_b = np.argmax(bert_logits, axis=1)

bert_acc = float(accuracy_score(y_test, y_pred_b))
bert_f1w = float(f1_score(y_test, y_pred_b, average="weighted"))
bert_precw = float(precision_score(y_test, y_pred_b, average="weighted", zero_division=0))
bert_recw = float(recall_score(y_test, y_pred_b, average="weighted", zero_division=0))

print("\n[DISTILBERT TEST METRICS]")
print("Accuracy:", round(bert_acc, 4))
print("F1(w):  ", round(bert_f1w, 4))
print("\nClassification Report (DistilBERT):\n")
print(classification_report(y_test, y_pred_b, target_names=class_names))

cm_b = confusion_matrix(y_test, y_pred_b)
plot_confusion(cm_b, class_names, "Confusion Matrix: DistilBERT")

# Save DistilBERT artifacts
trainer.save_model(BERT_DIR)
tokenizer.save_pretrained(BERT_DIR)
joblib.dump(label_encoder, os.path.join(BERT_DIR, "label_encoder.pkl"))
with open(os.path.join(BERT_DIR, "metrics.json"), "w") as f:
    json.dump({
        "eval": bert_eval,
        "test_accuracy": bert_acc,
        "test_f1_weighted": bert_f1w,
        "test_precision_weighted": bert_precw,
        "test_recall_weighted": bert_recw,
        "train_time_sec": bert_train_time
    }, f, indent=2)

print("Saved DistilBERT artifacts ->", BERT_DIR)


# ============================================================
# 5) VISUAL COMPARISON (Accuracy + F1w)
# ============================================================
df_metrics = pd.DataFrame([
    {"model": "Classical", "accuracy": classical_acc, "f1_weighted": classical_f1w, "train_time_sec": classical_train_time},
    {"model": "DistilBERT", "accuracy": bert_acc, "f1_weighted": bert_f1w, "train_time_sec": bert_train_time},
])

print("\nCOMPARISON TABLE:\n", df_metrics.to_string(index=False))
plot_model_comparison(df_metrics, "Model Comparison: Classical vs DistilBERT")

# Also show training time comparison (optional)
plt.figure()
plt.bar(df_metrics["model"], df_metrics["train_time_sec"])
plt.title("Training Time (seconds)")
plt.ylabel("Seconds")
plt.tight_layout()
plt.show()


# ============================================================
# 6) SAVE BEST OVERALL (for Streamlit later)
# ============================================================
best_type = "distilbert" if bert_acc > classical_acc else "classical"
print("\nBEST OVERALL MODEL:", best_type.upper())

best_meta = {
    "best_type": best_type,
    "class_names": class_names,
    "classical": {
        "test_accuracy": classical_acc,
        "test_f1_weighted": classical_f1w,
        "train_time_sec": classical_train_time,
        "best_model_name": best_classical_name
    },
    "distilbert": {
        "test_accuracy": bert_acc,
        "test_f1_weighted": bert_f1w,
        "train_time_sec": bert_train_time
    }
}
with open(os.path.join(OUT_DIR, "best_model_meta.json"), "w") as f:
    json.dump(best_meta, f, indent=2)

# Make Streamlit loading simple
if best_type == "classical":
    joblib.dump(best_classical_pipe, os.path.join(OUT_DIR, "best_model.pkl"))
    joblib.dump(label_encoder, os.path.join(OUT_DIR, "label_encoder.pkl"))
else:
    # DistilBERT already saved in BERT_DIR, store pointer + label encoder copy
    with open(os.path.join(OUT_DIR, "distilbert_dir.txt"), "w") as f:
        f.write(BERT_DIR)
    joblib.dump(label_encoder, os.path.join(OUT_DIR, "label_encoder.pkl"))

print("Saved BEST model artifacts ->", OUT_DIR)

import shap
from lime.lime_text import LimeTextExplainer
import torch
import numpy as np

print("\n SHAP for Classical Model (TF-IDF + Best Classifier)")

# ----------------------------
# Helpers (fix .iloc issue)
# ----------------------------
def get_item(x, i):
    return x.iloc[i] if hasattr(x, "iloc") else x[i]

def get_slice(x, s, e):
    return x.iloc[s:e] if hasattr(x, "iloc") else x[s:e]

# Extract TF-IDF vectorizer & classifier
vectorizer = best_classical_pipe.named_steps["tfidf"]
clf = best_classical_pipe.named_steps["clf"]

# safe input helper: replace empty/whitespace, truncate very long texts
def safe_texts(items, max_chars=1500, empty_token="[EMPTY]"):
    texts = [str(t) for t in items]
    out = []
    for t in texts:
        t = t.strip()
        if not t:
            t = empty_token
        if len(t) > max_chars:
            t = t[:max_chars]
        out.append(t)
    return out

# prepare sample (single item) and a small batch for plotting
sample_text = safe_texts([get_item(X_test, 0)])[0]
sample_batch = safe_texts(get_slice(X_test, 0, 5))

print("\n📝 Sample text:", sample_text)

# model wrapper: accepts iterable of raw texts, returns numpy (n_samples, n_classes)
def model_proba(texts):
    texts = safe_texts(texts)
    X_vec = vectorizer.transform(texts)
    return clf.predict_proba(X_vec)

# Try text-level masker first (token-level SHAP)
try:
    masker = shap.maskers.Text()
    explainer = shap.Explainer(model_proba, masker, output_names=getattr(clf, "classes_", None))
    shap_values = explainer([sample_text])
    print("Using Text masker explainer (token-level SHAP).")
    shap.plots.text(shap_values[0])
except Exception as e_text:
    print("Text masker explainer failed:", repr(e_text))
    # fallback: TreeExplainer on numeric TF-IDF features (small background only)
    try:
        bg_n = min(200, len(X_train))
        background = vectorizer.transform(safe_texts(get_slice(X_train, 0, bg_n))).toarray()
        explainer = shap.TreeExplainer(clf, data=background)

        X_sample = vectorizer.transform(sample_batch).toarray()
        shap_values = explainer.shap_values(X_sample)
        print("Using TreeExplainer on TF-IDF features.")
        feat_names = vectorizer.get_feature_names_out()
        class_idx = 1 if isinstance(shap_values, list) and len(shap_values) > 1 else 0
        shap.summary_plot(shap_values[class_idx], X_sample, feature_names=feat_names)
    except Exception as e_tree:
        print("TreeExplainer fallback also failed:", repr(e_tree))
        raise

# --------------------------
# LIME for Classical Model
# --------------------------
class_names = list(label_encoder.classes_)
lime_explainer = LimeTextExplainer(class_names=class_names)

lime_exp = lime_explainer.explain_instance(
    sample_text,
    classifier_fn=lambda x: clf.predict_proba(vectorizer.transform(safe_texts(x))),
    num_features=10
)

try:
    lime_exp.show_in_notebook()
except Exception:
    print(lime_exp.as_list())

# --------------------------
# SHAP for DistilBERT Model (FIXED)
# --------------------------
print("\n SHAP for DistilBERT Model (Transformers)")

def bert_predict(texts):
    texts = safe_texts(texts)
    enc = tokenizer(
        list(texts),
        padding=True,
        truncation=True,
        max_length=64,
        return_tensors="pt"
    ).to(device)

    with torch.no_grad():
        outputs = model(**enc)

    probs = outputs.logits.softmax(dim=1).detach().cpu().numpy()
    if probs.ndim == 1:
        probs = probs.reshape(1, -1)
    return probs

try:
    # ✅ Correct masker for SHAP text (keeps shap.plots.text visuals)
    try:
        bert_masker = shap.maskers.Text(tokenizer)
    except Exception:
        bert_masker = shap.maskers.Text()

    bert_explainer = shap.Explainer(
        bert_predict,
        bert_masker,
        output_names=class_names,
        algorithm="partition"
    )

    shap_values_bert = bert_explainer([sample_text])
    print("BERT explainer created.")
    shap.plots.text(shap_values_bert[0])

except Exception as e_bert:
    print("BERT SHAP explainer failed:", repr(e_bert))
    # minimal fallback: try without partition
    try:
        bert_explainer = shap.Explainer(bert_predict, shap.maskers.Text(), output_names=class_names)
        shap_values_bert = bert_explainer([sample_text])
        shap.plots.text(shap_values_bert[0])
    except Exception as e_fallback:
        print("Fallback BERT explainer also failed:", repr(e_fallback))

# --------------------------
# LIME for DistilBERT
# --------------------------
print("\n LIME for DistilBERT Model")
lime_exp_bert = lime_explainer.explain_instance(
    sample_text,
    classifier_fn=bert_predict,
    num_features=10
)

try:
    lime_exp_bert.show_in_notebook()
except Exception:
    print(lime_exp_bert.as_list())

print("\n SHAP & LIME Visualizations Completed!")

