# -*- coding: utf-8 -*-
"""Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12rXnqzcbUfP-ldr9trmV4aZheo41_ZMl
"""

import pandas as pd
import numpy as np
import re
import string

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split


# ----------------------------
# Load
# ----------------------------
df = pd.read_excel("202305_CYBERBYSTANDER.xlsx")

df.head()
df.info()
df.isnull().sum()
df.duplicated().sum()

# ----------------------------
# Basic cleaning: drop null tweet_id
# ----------------------------
df_cleaned = df.dropna(subset=["tweet_id"]).reset_index(drop=True)
print("Rows after dropping null tweet_id values:", df_cleaned.shape)
cols_to_drop = ["sentiment", "Class label", "Bystander Roles Label"]
df_cleaned = df_cleaned.drop(columns=cols_to_drop)

print("Shape after dropping columns:", df_cleaned.shape)
df_cleaned.info()
df_cleaned.head()

# ----------------------------
# EDA
# ----------------------------

tox_cols = [
    "Insult", "Threat", "Identity_Attack",
    "Profanity", "Toxicity", "Severe_Toxicity"
]

# Distribution of toxicity-related scores
df[tox_cols].hist(figsize=(12, 8))
plt.show()

# Top toxic tweets
print(
    df.sort_values(by="Toxicity", ascending=False)[["text", "Toxicity"]].head(10)
)

# Toxicity vs Retweet Count
sns.scatterplot(x=df["Toxicity"], y=df["retweet_count"])
plt.title("Toxicity vs Retweet Count")
plt.show()


# ----------------------------
# Final feature table
# ----------------------------

final_features = [
    "text",
    "Insult", "Threat", "Identity_Attack",
    "Profanity", "Toxicity", "Severe_Toxicity"
]

df_final = df_cleaned[final_features] \
    .dropna(subset=["text"]) \
    .reset_index(drop=True)

print(df_final.head())


# ----------------------------
# Scale regression targets
# ----------------------------

scaler = MinMaxScaler()
df_final[tox_cols] = scaler.fit_transform(df_final[tox_cols])


# ----------------------------
# Text cleaning
# ----------------------------

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"@\w+|\#", "", text)          # mentions + hashtag symbol
    text = re.sub(r"https?:\/\/\S+", "", text)   # URLs
    text = text.translate(str.maketrans("", "", string.punctuation))
    text = re.sub(r"\s+", " ", text).strip()
    return text

df_final["text"] = df_final["text"].apply(clean_text)

print(df_final.head())

# Save cleaned dataset (same behavior)
cleaned_file_path = "cleaned_cyberbullying_dataset.csv"
df_final.to_csv(cleaned_file_path, index=False)

df_final.info()
df_final.head()

# ----------------------------
# TF-IDF + splits (same behavior)
# ----------------------------
tfidf_vectorizer = TfidfVectorizer(max_features=2000, stop_words="english")
X_text_tfidf = tfidf_vectorizer.fit_transform(df_final["text"])

y_regression = df_final[tox_cols]

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_text_tfidf, y_regression, test_size=0.2, random_state=42
)

from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor
)
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_squared_error, r2_score
from xgboost import XGBRegressor
import pandas as pd


# -----------------------------
# 1) Models (same set)
# -----------------------------


reg_pool = {
    "RandomForest": RandomForestRegressor(random_state=42),
    "LinearRegression": LinearRegression(),
    "KNN": KNeighborsRegressor(),
    "GradientBoosting": GradientBoostingRegressor(),
    "MLP": MLPRegressor(max_iter=1000, random_state=42),
    "XGBRegressor": XGBRegressor(objective="reg:squarederror")
}

# -----------------------------
# 2) Containers for results
# -----------------------------

reg_rows = []


# -----------------------------
# 4) Multi-output regression evaluation (ALL OUTPUTS)
# -----------------------------
target_names = list(y_train_reg.columns)  # keeps your original column names

for model_name, base_model in reg_pool.items():
    wrapper = MultiOutputRegressor(base_model)
    wrapper.fit(X_train_reg, y_train_reg)

    pred = wrapper.predict(X_test_reg)

    # arrays of length = num_outputs
    mse_vals = mean_squared_error(y_test_reg, pred, multioutput="raw_values")
    r2_vals = r2_score(y_test_reg, pred, multioutput="raw_values")

    row = {"Model": model_name}

    # expand into columns dynamically
    for j, target in enumerate(target_names):
        row[f"{target} MSE"] = round(float(mse_vals[j]), 4)
        row[f"{target} R2"] = round(float(r2_vals[j]), 4)

    reg_rows.append(row)

df = pd.DataFrame(reg_rows).round(4)

mse_cols = ["Model"] + [c for c in df.columns if "MSE" in c]
r2_cols  = ["Model"] + [c for c in df.columns if "R2" in c]

print("\n🔹 Mean Squared Error (per target)")
print(df[mse_cols].to_string(index=False))

print("\n🔹 R² Score (per target)")
print(df[r2_cols].to_string(index=False))

import joblib

# -----------------------------
# Persist trained artifacts
# -----------------------------
vec_path = "vectorizer.pkl"
cls_path = "cls_multi_model.pkl"
reg_path = "reg_multi_model.pkl"

joblib.dump(tfidf_vectorizer, vec_path)
joblib.dump(clf, cls_path)
joblib.dump(rf_multi_reg, reg_path)

print(f"Saved: {vec_path}, {cls_path}, {reg_path}")





